version: "3.4"
services:
  dotnet-app: #docker run -it -v ${PWD}:/work -p 5000:5000 --name my-app-in-container my-image 
    container_name: my-app-in-container
    image: my-image
    build:
      context: .
    #   target: debug
    volumes:
    - ./:/work/
    # ports:
    #   - 5000:5000